encyclopedia/urls.py
from django.urls import path

from . import views
app_name = 'wiki'
urlpatterns = [
    path('', views.index, name='index'),
    path('wiki/<str:title>', views.wiki, name='entry'),
    path('search/', views.search, name='search'),
    path('new_entry/', views.new_entry, name='new_entry'),
    path('edit_entry/<str:title>', views.edit_entry, name='edit_entry'),
    path('random/', views.random, name='random')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from . import util
from random import choice
from markdown2 import Markdown

class newSearchForm(forms.Form):#innherits from forms.Form
    search = forms.CharField(
        widget= forms.TextInput(attrs={
            'placeholder':'Search',
            'class': 'd-inline',
            'style': 'width: 70%'
        }),
        label=''
    )

class newEntryForm(forms.Form):
    title = forms.CharField(
        widget = forms.TextInput(attrs={'placeholder':'What\'s the Title?'}),
        label=''
    )
    content = forms.CharField(
        widget = forms.Textarea(attrs={
            'placeholder':'Use Markdown formatting to style this entry\'s content.',
            'cols': '40',
            'rows': '5',
            'class': 'my-2'
        }),
        label=''
    )

class editEntryForm(forms.Form):
    title = forms.CharField(
        widget = forms.TextInput(attrs={'hidden': 'True'}),
        label=''
    )
    content = forms.CharField(
        widget = forms.Textarea(attrs={'cols': '40', 'rows': '5'}),
        label=''
    )

def markdowner(title):
    #This method converts MD into HTML
    return Markdown().convert(util.get_entry(title))

def index(request):
    return render(request, 'encyclopedia/index.html', {
        'entries': util.list_entries(),
        'header': 'All Pages',
        'form': newSearchForm()
    })

def wiki(request, title):
    if util.get_entry(title):
        return render(request, 'encyclopedia/entry.html', {
            'title': title,
            'entry': markdowner(title),
            'form': newSearchForm()
        })
    return render(request, 'encyclopedia/entry.html', {
            'title': title,
            'form': newSearchForm()
        })

def search(request):
    form = newSearchForm(request.POST)
    if form.is_valid():
            title = form.cleaned_data['search']
            entries_substring = []
            for entry in util.list_entries():
                if title.lower() in entry.lower():
                    if title.lower() != entry.lower():
                        entries_substring.append(entry)
                    else:
                        return render(request, 'encyclopedia/entry.html', {
                        'title': title,
                        'entry': markdowner(title),
                        'form': newSearchForm()
                        })
            if len(entries_substring):
                return render(request, 'encyclopedia/index.html', {
                'entries': entries_substring,
                'header': 'Matching Results',
                'form': newSearchForm()
                })
    #if there are no matching results for the search, then return All Pages List
    return render(request, 'encyclopedia/index.html', {
    'entries': util.list_entries(),
    'header': 'All Pages',
    'form': newSearchForm()
    })

def new_entry(request):
    if request.method == 'POST':
        form = newEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            for entry in util.list_entries():
                if title.lower() == entry.lower():
                    return render(request, 'encyclopedia/new_entry.html', {
                    'header': 'New Entry',
                    'form': newSearchForm(),
                    'new_entry_form': form,
                    'error_message': 'This Title already exist. Please try a different one'
                    })
            try:
                util.save_entry(title, content)
                return render(request, 'encyclopedia/entry.html', {
                    'title': title,
                    'entry': markdowner(title),
                    'form': newSearchForm()
                })
            except Exception as e:
            #If an error is encountered, return the form with its content and display an error message
                return render(request, 'encyclopedia/new_entry.html', {
            'header': 'New Entry',
            'form': newSearchForm(),
            'new_entry_form': form,
            'error_message': e
            })
    return render(request, 'encyclopedia/new_entry.html', {
        'header': 'New Entry',
        'form': newSearchForm(),
        'new_entry_form': newEntryForm(),
    })

def edit_entry(request, title):
    if request.method == 'POST':
        form = editEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            try:
                util.save_entry(title, content)
                return render(request, 'encyclopedia/entry.html', {
                    'title': title,
                    'entry': markdowner(title),
                    'form': newSearchForm()
                })
            except Exception as e:
                return render(request, 'encyclopedia/new_entry.html', {
            'header': 'New Entry',
            'form': newSearchForm(),
            'new_entry_form': form,
            'error_message': e
            })
    return render(request, 'encyclopedia/edit_entry.html', {
        'header': 'Edit Entry',
        'title': title,
        'editForm': editEntryForm( 
            initial = {'title': title, 'content': util.get_entry( title )},
            auto_id = 'False'
        ),
        'form': newSearchForm()
    })

def random(request):
    entry = choice(util.list_entries())
    return render(request, 'encyclopedia/entry.html', {
        'title': entry,
        'entry': markdowner(entry),
        'form': newSearchForm()
    })

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <h3>{{ header }}</h3>
    <h6>{{ title }}</h6>
    <h6 style="color:red">{{ error_message }}</h6>
    <form  action="{% url 'wiki:edit_entry' title %}" method="POST">
        {% csrf_token %}
        {{ editForm }}
        <div class="form_footer">
            <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax" class="small">Learn more about Markdown formatting</a>
            <input type="submit" placeholder="Save">
        </div>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<a href="{% url 'wiki:edit_entry' title %}" class="small">Edit content</a>
<div class="w-75">
    {{ entry | safe | default:"Upsss...We haven't found any matching entry with this name" }}
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h3>{{ header }}</h3>
    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search'%}" method="POST" class="search">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" class="my-2 d-inline p-1 text-white bg-dark rounded" value="Find">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h3>{{ header }}</h3>
    <h6 class="small text-danger">{{ error_message }}</h6>
    <form action="{% url 'wiki:new_entry' %}" method="POST">
        {% csrf_token %}
        {{ new_entry_form }}
    <div class="form_footer">
        <a href="https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax" class="small">Learn more about Markdown formatting</a>
        <input type="submit">
    </div>
    </form>
{% endblock %}